#!/bin/zsh

export PATH=/home/andrew/.local/bin:$PATH

alias nvim="~/.local/bin/lvim.AppImage"

source /usr/share/doc/fzf/examples/key-bindings.zsh

# Print tree structure in the preview window
# export FZF_ALT_C_OPTS="--preview 'tree -C {}'"

# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
--preview 'echo {}' --preview-window up:3:hidden:wrap
--bind 'ctrl-/:toggle-preview'
--bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
--color header:italic
--header 'Press CTRL-Y to copy command into clipboard'"

# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
--preview 'batcat -n --color=always {}'
--bind 'ctrl-/:change-preview-window(down|hidden|)'"
