#!/bin/zsh

alias dr="cd ~/dr2/"
alias drk="cd ~/dr2/keys/"

alias gpc="globalprotect connect"
alias gpd="globalprotect disconnect"
alias gps="globalprotect show --status"

# Load colours from pywal
(cat ~/.cache/wal/sequences &)

source ~/scripts/s.sh
source ~/scripts/ip.sh

alias nvim="~/Downloads/nvim.appimage"

# Testing this doesn't conflict with other binaries before moving it to a shared file
export PATH=/home/andrew/.local/bin:$PATH
