#!/bin/zsh

# For a full list of active aliases, run `alias`.

alias sup="sudo apt update && sudo apt dist-upgrade && sudo apt autoclean && sudo apt autoremove"
alias supSnap="sudo snap refresh"
alias sups="sup && sudo shutdown -h now"

alias d="cd ~/Dropbox"
alias ss="cd ~/Pictures/scrot/"

alias gs="git status"
alias gd="git diff"
alias gp="git push"
alias ez="$EDITOR ~/.zshrc"
alias sz="source ~/.zshrc"

alias  l="exa --icons --group-directories-first"
alias ll="l --long --header"
alias la="ll --all"
alias lt="ll --tree --level=3"

alias :q="exit"

alias bat="batcat"
