#!/bin/zsh

# For a full list of active aliases, run `alias`.

alias sup="sudo apt update && sudo apt dist-upgrade && sudo apt autoclean && sudo apt autoremove"
alias supSnap="sudo snap refresh"
alias sups="sup && sudo shutdown -h now"

alias d="cd ~/Dropbox"
alias ss="cd ~/Pictures/scrot/"

alias gs="git status"
alias gd="git diff"
alias gp="git push"

gtfo() {
  git clean -f $1
  git restore $1
}

alias ez="${EDITOR} ${XDG_CONFIG_HOME}/zsh/.zshrc"
alias sz="source ${XDG_CONFIG_HOME}/zsh/.zshrc"

alias  l="exa --icons --group-directories-first"
alias ll="l --long --header"
alias la="ll --all"
alias lt="ll --tree --level=3"

alias :q="exit"

alias bat="batcat"

alias v="nvim"
alias vim="nvim"
